"""agregar foto_url a TEAM

Revision ID: 8341fdaf851b
Revises: ceee730de502
Create Date: 2026-05-30 21:05:17.483214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8341fdaf851b'
down_revision: Union[str, Sequence[str], None] = 'ceee730de502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('foto_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'foto_url')
    # ### end Alembic commands ###
